### ISSUE TITLE
Implement token storage and consolidate storage `kind`

### ISSUE THREAD

**Issue by edclement** [xlts-dev/verdaccio-google-cloud-storage#1]
Using the default `local-storage` plugin has the following behavior:
1. JWT signing secret is stored to `<storage_path>/.verdaccio-db.json` under a top level key of `secret` in the JSON file.
2. The list of published packages is stored to `<storage_path>/.verdaccio-db.json` under a top level key of `list` in the JSON file. This list is a simple array of published package names (only names, no version info). When the Verdaccio UI loads and displays the list of published packages it uses this list when building the results.
3. JWT token metadata is stored to `<storage_path>/.token-db.json`. This file contains metata on each issued JWT token (NOT the full JWT token) and is used to provide responses to the `npm token` command.

The existing `verdaccio-google-storage` plugin has the following behavior:
1. JWT signing secret is stored to GCP Datastore under a `kind` named "*Secret*". The secret is the only entity stored under this `kind` and has a single "*secret*" property where the value of the JWT signing secret value resides.
2. The list of published packages is stored to GCP Datastore under a `kind` named "*VerdaccioDataStore*" (this is the default name but is configurable). Each published package name is stored as a separate entity with a single property named "*name*" that holds the package name. When the Verdaccio UI loads and displays the list of published packages it does a query against this `kind` with no filters as part of building the list.
3. JWT token metadata related storage is NOT implemented at all.

Because the current `verdaccio-google-storage` plugin lacks implementation of the necessary token actions to store/retrieve user token metadata,  the `npm create token` command fails. Additional details:
* In order to generate tokens and store token metadata the following functions must be implemented in a storage plugin: https://github.com/verdaccio/monorepo/blob/v10.0.6/core/types/index.d.ts#L377
* The `saveToken`, `deleteToken`, and `readTokens` functions are implemented in the default `local-storage` plugin: https://github.com/verdaccio/monorepo/blob/v10.0.6/plugins/local-storage/src/token.ts
* These functions explicitly reject in the `verdaccio-google-cloud` storage plugin: https://github.com/verdaccio/monorepo/blob/v10.0.6/plugins/google-cloud/src/data-storage.ts#L70

## Proposal
* Consolidate all data storage down to a single GCP Datastore `kind`, adding additional metadata to each entity stored so records can be filtered based on the type of record being retrieved.
* Implement the `saveToken`, `deleteToken`, and `readTokens` functions. The token metadata records would be stored under the same `kind` used for storing package names. An additional "*type*" property will be added to the entity with a static value of `token` so when retrieving/listing tokens a filter of `type=token` will be applied.
* Refactor the current storage of package names to add an additional "*type*" property to the entity with a static value of `package` so when listing package names a filter of `type=package` will be applied.
* One of two possible changes to the implementation of the JWT signing secret:
  1. **Preferred** - Use GCP Secret Manager for storing/retrieving the JWT signing secret. This would be more secure then using GCP Datastore and would allow for better IAM management of the JWT signing secret. Right now anyone who has read access to GCP Datastore can view and potentially modify this secret, breaking customer tokens.
  2.  Refactor the current storage of JWT secret to add an additional "*type*" property to the entity with a static value of `secret` so when retrieving the secret a filter of `type=secret` will be applied.

**Comment by Splaktar** [comment]
I am on board with all of this, including GCP Secret Manager. However, can you please explain why using the same Entity kind for packages and tokens and filtering by a type property is better?

**Comment by edclement** [comment]
@Splaktar I don't think it's necessarily "better" but based on the GCP datastore docs the entities held within a `kind`: 
> An entity has one or more named properties, each of which can have one or more values. Entities of the same kind do not need to have the same properties, and an entity's values for a given property do not all need to be of the same data type. (If necessary, an application can establish and enforce such restrictions in its own data model.)

...that came from [here](https://cloud.google.com/datastore/docs/concepts/entities). Based on this info I thought it might just make sense to have a single "`kind`" for Verdaccio that holds the different types of data. Given our use case and the fact that we will likely have an absolute max of maybe tens of thousands of records I didn't think it would be necessary to split the data out into different `kind`s. We can always add a index to the `type` property later if we need to.

I'm not opposed to using two different `kind`s though for packages vs tokens. Let me know your preference.

**Comment by Splaktar** [comment]
> The `kind` of the entity, which categorizes it for the purpose of queries
>
> Each entity is of a particular `kind`, which categorizes the entity for the purpose of queries: for instance, a task list application might represent each task to complete with an entity of kind `Task`.

I think that we should probably go with `VerdaccioPackage` and `VerdaccioToken` as the Entity `kind`s. No `kind` for secrets as those should go in GCP Secret Manager.

**Comment by edclement** [comment]
> I think that we should probably go with VerdaccioPackage and VerdaccioToken as the Entity kinds. No kind for secrets as those should go in GCP Secret Manager.

Sounds good to me. I'll go this route.

> Is there any metadata that needs to be stored for users? Or they only have a username/password as defined in the htpasswd file?

No metadata. Verdaccio relies solely on the username/password as defined in the `htpasswd` file. Eventually we may want to write our own auth plugin that stores this same info in GCP datastore as a `kind` of `VerdaccioAuth` instead of a file on the file system. We could add metadata at that point about the customer (for our own informational purposes) and also provide an enable/disable flag. This would have the following benefits:
1. We wouldn't have to maintain that htpasswd config in the helm values file.
2. We would NOT have to redeploy everytime a user is added or removed.
3. We could build a simple web based admin tool to maintain the users/passwords.

**Comment by Splaktar** [comment]
Yes, I agree that we need to move in that direction once scalability and reliability are fully solved. Feel free to write up an issue for that.

**Comment by edclement** [comment]
> Yes, I agree that we need to move in that direction once scalability and reliability are fully solved. Feel free to write up an issue for that.

It looks like this issue already covers it: https://github.com/xlts-dev/registry/issues/23. I'll mention this issue there.

**Comment by Splaktar** [comment]
I love the idea of a migration script. The rest of the plan LGTM as well!

**Comment by edclement** [comment]
Related to this effort: Verdaccio is slow listing packages: https://github.com/xlts-dev/verdaccio-google-cloud-storage/issues/2

**Comment by edclement** [comment]
Issues have been opened for:
- Unit tests - https://github.com/xlts-dev/verdaccio-google-cloud-storage/issues/3
- Search - https://github.com/xlts-dev/verdaccio-google-cloud-storage/issues/4
- data-storage.ts clean-up - https://github.com/xlts-dev/verdaccio-google-cloud-storage/issues/5
- IAC - https://github.com/xlts-dev/registry/issues/30

Per slack discussion, Plugin deployment will occur using a pre-baked docker image since using k8s init container to pull the plugin and perform `npm install` adds about 3 minutes to the pod start-up time which is not acceptable.

**Comment by Splaktar** [comment]
> > Yes, I agree that we need to move in that direction once scalability and reliability are fully solved. Feel free to write up an issue for that.
> 
> It looks like this issue already covers it: [xlts-dev/registry#23](https://github.com/xlts-dev/registry/issues/23). I'll mention this issue there.

We should probably track the possibility of creating a GCP-based Auth plugin in this public repo rather than in that private repo.
